version: "3"

services: 
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: "123456789"
    restart: always
    volumes:
        - ./data:/var/lib/postgresql/data 
    ports: 
        - 5435:5432
  app:
    build: .
    command: npm start
    ports: 
      - 3000:3000 
    restart: always
    depends_on: 
      - db
    volumes: 
      - .:/usr/app
    